version: '3'
services:
  pyrandseqbot-backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        PROJECT_USER: pyrandseqbot
    image: pyrandseqbot-backend:${ENV}
    container_name: pyrandseqbot-backend-${ENV}
    command: python run.py
    restart: always
    networks:
      - pyrandseqbot-${ENV}
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    volumes:
      - ${LOGS_VOLUME_DIR}/${ENV}:/home/pyrandseqbot/pyrandseqbot/.logs
      - ${DB_VOLUME_DIR}/${ENV}:/home/pyrandseqbot/pyrandseqbot/db
networks:
  pyrandseqbot:
    external:
      name: pyrandseqbot-${ENV}
